// Pure lyric + quality utilities ported VERBATIM from the monolith (DATA-01).
//   parseLRC          ← legacy/index.html:2517-2533
//   inferQualityFromUrl ← legacy/index.html:1747-1758
// The legacy neteaseQualityToTag / kuwoQualityToTag helpers are intentionally NOT
// ported (marked 暂时保留不再使用 / "kept but unused" in the monolith).

export interface LyricLine {
	time: number;
	text: string;
	/** True when this line was generated by splitting a parenthesized clause out of its
	 *  parent line (the second-language version that came tagged inline). The renderer can
	 *  hide its translation when settings.lyricsHideParenTranslation is true. */
	fromParen?: boolean;
}

export interface QualityInfo {
	tag: string | null;
	label: string;
}

/**
 * Parse `[mm:ss.xxx]` LRC text into a time-sorted `{time,text}[]` (seconds).
 * Blank lines and lines with no timestamp are dropped. Ported verbatim from
 * legacy/index.html:2517-2533.
 */
export function parseLRC(txt: string): LyricLine[] {
	if (!txt) return [];
	const lines = txt.split(/\r?\n/);
	const reg = /\[(\d{1,2}):(\d{1,2})(?:\.(\d{1,3}))?\]/;
	const out: LyricLine[] = [];
	for (const line of lines) {
		const m = reg.exec(line);
		if (!m) continue;
		const min = parseInt(m[1], 10) || 0;
		const sec = parseInt(m[2], 10) || 0;
		const ms = m[3] ? parseInt(m[3].padEnd(3, '0'), 10) : 0;
		const time = min * 60 + sec + ms / 1000;
		const text = line.replace(reg, '').trim();
		if (text) out.push({ time, text });
	}
	out.sort((a, b) => a.time - b.time);
	return out;
}

/**
 * A coarse Unicode-script classification of a line body, used to tell an original
 * lyric line apart from its embedded translation. `'other'` covers digit/punctuation-
 * only or empty lines (no countable letter present).
 */
export type Script = 'han' | 'kana' | 'hangul' | 'latin' | 'other';

/**
 * Return the dominant script of `text` by counting codepoints per script class.
 *
 * Uses ES2018 Unicode property escapes (`\p{Script=...}`, Baseline since Safari 11.1 /
 * Chrome 64) — the `u` flag is mandatory and we iterate by codepoint (`for...of`) so
 * astral-plane CJK extension characters count as single units.
 *
 * Heuristic (A1): Japanese mixes kanji (Han) with kana; a pure max-count would mislabel
 * a kanji-heavy JP line as `'han'` (== Chinese). Therefore ANY kana presence ⇒ `'kana'`,
 * regardless of Han count. Otherwise the largest of han/hangul/latin wins; ties favour
 * han, then hangul, then latin. A line with no countable letters returns `'other'`.
 */
export function dominantScript(text: string): Script {
	let han = 0;
	let kana = 0;
	let hangul = 0;
	let latin = 0;
	for (const ch of text) {
		if (/\p{Script=Han}/u.test(ch)) han++;
		else if (/\p{Script=Hiragana}/u.test(ch) || /\p{Script=Katakana}/u.test(ch)) kana++;
		else if (/\p{Script=Hangul}/u.test(ch)) hangul++;
		else if (/\p{Script=Latin}/u.test(ch)) latin++;
		// whitespace / punctuation / digits are not counted
	}
	// Any kana presence ⇒ Japanese, even when kanji dominates the count (A1).
	if (kana > 0) return 'kana';
	const max = Math.max(han, hangul, latin);
	if (max === 0) return 'other';
	if (han === max) return 'han';
	if (hangul === max) return 'hangul';
	return 'latin';
}

/**
 * Reorder lines so that within each same-`time` group the ORIGINAL lyric (the line whose
 * script matches the song's dominant language) is rendered ABOVE its translation (D-04/D-05).
 *
 * Why: some upstream LRCs ship the translation first and the original second within a
 * shared timestamp; the group-highlight anchor in NowPlaying.svelte locks onto the FIRST
 * entry of a group, so the original must come first for the highlight to track the sung line.
 *
 * Algorithm:
 *   1. Compute the song-dominant script across ALL line bodies (the "original language"
 *      baseline — A1 mitigation: decided over the whole song, not per-line).
 *   2. Walk consecutive same-`time` groups. Within a group, if at least one line's
 *      dominantScript === songDominant and at least one sibling's !== songDominant, move
 *      the FIRST song-dominant (original) line to the front of the group.
 *   3. Pure single-script songs (no mismatched siblings) pass through unchanged.
 *   4. Stable: the relative order of all non-moved lines is preserved.
 *
 * MUST run BEFORE splitParenLines — split emits multiple same-timestamp siblings, which
 * would pollute the original/translation grouping this function inspects.
 */
export function reorderPairs(lines: LyricLine[]): LyricLine[] {
	if (lines.length < 2) return lines.slice();

	// 1. Song-dominant script over all line bodies.
	let han = 0;
	let kana = 0;
	let hangul = 0;
	let latin = 0;
	for (const line of lines) {
		switch (dominantScript(line.text)) {
			case 'han':
				han++;
				break;
			case 'kana':
				kana++;
				break;
			case 'hangul':
				hangul++;
				break;
			case 'latin':
				latin++;
				break;
			default:
				break;
		}
	}
	// In this app Han (Simplified/Traditional Chinese) is overwhelmingly the user's
	// TRANSLATION target, never the foreign original. So if the song contains ANY non-Han
	// script the original language is that foreign script — even when Han is the per-line
	// count majority (a 1-original/2-translation-fragment LRC still has the foreign line as
	// the original). Foreign scripts are ranked kana > hangul > latin by count. Only a song
	// with no foreign script at all (pure-CN) keeps Han as dominant — and such songs have no
	// mismatched siblings, so reorder is a no-op regardless.
	const foreignMax = Math.max(kana, hangul, latin);
	let songDominant: Script;
	if (foreignMax > 0) {
		if (kana === foreignMax) songDominant = 'kana';
		else if (hangul === foreignMax) songDominant = 'hangul';
		else songDominant = 'latin';
	} else if (han > 0) {
		songDominant = 'han';
	} else {
		songDominant = 'other';
	}

	const out: LyricLine[] = [];
	let i = 0;
	while (i < lines.length) {
		// Collect the consecutive same-`time` group starting at i.
		let j = i + 1;
		while (j < lines.length && lines[j].time === lines[i].time) j++;
		const group = lines.slice(i, j);
		i = j;

		if (group.length < 2) {
			out.push(...group);
			continue;
		}
		const hasOriginal = group.some((l) => dominantScript(l.text) === songDominant);
		const hasMismatch = group.some((l) => dominantScript(l.text) !== songDominant);
		if (!hasOriginal || !hasMismatch) {
			// Pure single-script (or no original) group — leave order unchanged.
			out.push(...group);
			continue;
		}
		// Move the first original (song-dominant) line to the front; keep all others stable.
		const origIdx = group.findIndex((l) => dominantScript(l.text) === songDominant);
		const reordered = [group[origIdx], ...group.filter((_, k) => k !== origIdx)];
		out.push(...reordered);
	}
	return out;
}

/**
 * Split a line containing one or more `(...)` / `（...）` clauses into separate LyricLine
 * entries that share the same timestamp. Useful when the upstream LRC encodes a translated
 * version inline next to the original — the user wants the translation to live on its own
 * line so the per-part translation pipeline can process it independently (English original
 * stays as-is when English is whitelisted; the parenthesised simplified-Chinese clause is
 * still translated to the user's target language). Lines without parens pass through
 * untouched. The returned entries carry `fromParen: true` for clauses that were extracted
 * out of their parent so the renderer can optionally hide their translations.
 *
 * Conventions (D-07/D-08/D-09):
 * - All 9 bracket pairs are recognised: （） () 【】 [] ［］ 「」 『』 〈〉 《》. Each open is
 *   matched to its OWN matching close (no cross-pairing — Pitfall 4). Timestamps are already
 *   stripped by parseLRC, so bare `[]` is safe here.
 * - A clause is split out as `{ fromParen: true }` ONLY when its dominant script DIFFERS from
 *   the line's main (de-bracketed) text. A same-script clause (backing vocals `(oh oh)`,
 *   `「真的」`) is left INLINE and is never emitted as `fromParen` — the structural never-drop
 *   guarantee (LYR-05): an original lyric can never be hidden because it is never extracted.
 * - A line that is ALREADY only a bracketed clause / section marker (e.g. `[Chorus]`, `【副歌】`,
 *   `(我們可以...)`) — i.e. nothing remains after removing the split clauses — passes through as a
 *   normal line (no split, no `fromParen`).
 * - Multiple mismatched clauses in one line produce multiple sibling entries.
 * - Order is preserved: parent (mismatched clauses removed) first, then each split clause in order.
 */
// Pair-aware bracket regex: each open bracket is matched to its OWN close (Pitfall 4 —
// avoids （…】 cross-pairing that a single character class would allow).
const BRACKET_RE =
	/（([^）]*)）|\(([^)]*)\)|【([^】]*)】|\[([^\]]*)\]|［([^］]*)］|「([^」]*)」|『([^』]*)』|〈([^〉]*)〉|《([^》]*)》/g;

export function splitParenLines(lines: LyricLine[]): LyricLine[] {
	const out: LyricLine[] = [];
	for (const line of lines) {
		BRACKET_RE.lastIndex = 0;
		const matches = [...line.text.matchAll(BRACKET_RE)];
		if (!matches.length) {
			out.push(line);
			continue;
		}
		// Script of the main body = the line with ALL brackets removed (for the mismatch gate).
		const mainText = line.text.replace(BRACKET_RE, '').replace(/\s+/g, ' ').trim();
		const mainScript = dominantScript(mainText);

		// Decide per match: a clause whose script DIFFERS from the main body is split out;
		// a same-script clause is kept inline (never dropped).
		const splitOut: string[] = [];
		const toRemove: string[] = [];
		for (const m of matches) {
			// The inner capture is whichever alternation group matched (others are undefined).
			const inner = (m.slice(1).find((g) => g !== undefined) ?? '').trim();
			if (!inner) continue;
			if (dominantScript(inner) !== mainScript) {
				splitOut.push(inner);
				toRemove.push(m[0]); // the full bracketed span, to strip from the main line
			}
		}

		// Build `stripped` = original text minus ONLY the mismatched clauses that were split out.
		// Same-script clauses survive inside `stripped` (never-drop).
		let strippedRaw = line.text;
		for (const span of toRemove) {
			strippedRaw = strippedRaw.replace(span, '');
		}
		const stripped = strippedRaw.replace(/\s+/g, ' ').trim();

		// Whole-line bracket / section marker (nothing left after removing split clauses) → keep
		// the original line as-is (D-09). Also covers the no-mismatch case where toRemove is empty.
		if (!stripped) {
			out.push(line);
			continue;
		}

		out.push({ time: line.time, text: stripped });
		for (const inner of splitOut) {
			out.push({ time: line.time, text: inner, fromParen: true });
		}
	}
	return out;
}

/**
 * Pure seek-math helper (LYR-01): the fraction `time / duration` to pass to the player's
 * fraction-based seek, or `null` when the duration is unusable (≤ 0 or non-finite). DOM-free
 * and store-free so the seek math is node-testable; the component multiplies/guards via this.
 */
export function lineSeekFraction(time: number, duration: number): number | null {
	return duration > 0 && Number.isFinite(duration) ? time / duration : null;
}

/**
 * quick-260919-1we: the currently-sung line at `now`. Lifted VERBATIM out of NowPlaying's inlined
 * `$derived.by` so the Nowbar's one-line variant runs the identical scan instead of a second copy
 * that could drift (the 2026-09-12 audit's exact failure mode — four of five copies of a guard
 * silently lacked a check).
 *
 * GROUP CONTRACT — do not "fix" this to return the last of a group. When several lines share a
 * timestamp (common in CN LRCs that ship the original + an inline translation as two consecutive
 * entries at the same time, plus splitParenLines' parent + paren clauses) they are all
 * simultaneously active for the user: it is one moment of the song. So `idx` anchors the group with
 * its FIRST entry (NowPlaying uses it as the scroll anchor) and `time` is the shared timestamp every
 * sibling compares itself against (`lines[i].time === time`).
 *
 * Before the first timestamp → `{ idx: -1, time: -1 }`. Past the last → the last line stays active
 * (no wrap, no reset).
 *
 * ponytail: O(n) forward scan, re-run once per `timeupdate` (~4 Hz) over tens of lines. Ceiling: a
 * pathological multi-thousand-line LRC. Upgrade path is a persistent cursor that only walks forward
 * from the previous index — not worth the seek/scrub invalidation it would need until a profile says
 * otherwise, and it will not.
 */
export function activeLineAt(
	lines: LyricLine[],
	now: number
): { idx: number; time: number } {
	let idx = -1;
	let time = -1;
	for (let i = 0; i < lines.length; i++) {
		const t = lines[i].time;
		if (t > now) break;
		if (t > time) {
			time = t;
			idx = i;
		}
	}
	return { idx, time };
}

/**
 * Infer a quality tag/label from an audio URL's file extension. Lossless extensions
 * → LOSSLESS; everything else → 320K. Ported verbatim from legacy/index.html:1747-1758.
 */
export function inferQualityFromUrl(url: string | null): QualityInfo {
	if (!url) return { tag: null, label: '' };
	const base = url.split('?')[0].toLowerCase();
	const m = base.match(/\.([a-z0-9]+)$/);
	const ext = m ? m[1] : '';
	const losslessExts = ['flac', 'wav', 'ape', 'alac', 'aiff'];
	if (losslessExts.includes(ext)) {
		return { tag: 'lossless', label: 'LOSSLESS' };
	}
	// 其他一律当作 320K 显示 — everything else displays as 320K.
	return { tag: '320k', label: '320K' };
}
